### ISSUE TITLE
Add modifier method

### ISSUE THREAD

**Issue by bobisjan** [sukima/ember-oo-modifiers#10]
What do you think about adding `modifier` "shortcut" method?

Similar to [Helper](https://api.emberjs.com/ember/release/classes/Helper) class and [helper](https://api.emberjs.com/ember/3.12/functions/@ember%2Fcomponent%2Fhelper/helper) method, the `modifier` method would be useful for common use cases.

**Usage**
```javascript
// app/modifiers/scroll-top.js
import { modifier } from 'ember-oo-modifers';

export default modifier(function scrollTop(element, [scrollPosition]) {
  element.scrollTop = scrollPosition;
});
```

**Implementation**
```javascript
// addon/-private/modifier.js
import Modifier from './modifier-native';

export default function modifier(modifierFn) {
  return class extends Modifier {
    didReceiveArguments(positional, named) {
      modifierFn(this.element, positional, named);
    }
  }
}
```

**Comment by sukima** [comment]
Sure, You up for a PR? If not it will take me some time, I'm kinda busy.

**Comment by bobisjan** [comment]
Yes, I will send one 🙌.
