### ISSUE TITLE
Custom modifier managers must define their capabilities

### ISSUE THREAD

**Issue by josemarluedke** [sukima/ember-oo-modifiers#12]
Using the latest ember canary gives the following deprecation: 

DEPRECATION: Custom modifier managers must define their capabilities using the capabilities() helper function [deprecation id: implicit-modifier-manager-capabilities]

**Comment by sukima** [comment]
Do you know how to fix this? I am having troubles keeping up with all the churn on this.

**Comment by josemarluedke** [comment]
I believe that this PR can give some ideas on how to fix it: https://github.com/emberjs/ember-render-modifiers/pull/13.

**Comment by sukima** [comment]
This is more confusing then a three headed bunny rabbit on PCP. Sorry I have no idea what to do.

https://github.com/emberjs/ember-render-modifiers/pull/13#issuecomment-523220429

**Comment by sukima** [comment]
https://github.com/sukima/ember-oo-modifiers/tree/bug/capabilities is what I got so far

**Comment by NullVoxPopuli** [comment]
@sukima that branch eliminated the Deprecation warning for me, and all my tests still pass.

errr -- now I have doubt
![image](https://user-images.githubusercontent.com/199018/64478992-a375c680-d17e-11e9-84c2-9a81f8cbfa99.png)

**Comment by NullVoxPopuli** [comment]
here we go: https://github.com/sukima/ember-oo-modifiers/pull/13

**Comment by chancancode** [comment]
This is fixed in v0.5.1 and v0.9.0!
