### ISSUE TITLE
Glimmer component unification

### ISSUE THREAD

**Issue by bobisjan** [sukima/ember-oo-modifiers#9]
Hi 👋,

would it make sense to unify the native `Modifer` API with Glimmer component API?

https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/component/addon/-private/component.ts#L147-L158

This would need to change the order of `constructor` arguments and using `args` property.

```javascript
class Modifier {
  // before
  constructor(attrs = {}, _owner) {
    setOwner(this, _owner);
    setProperties(this, attrs);
  }

  // after
  constructor(owner, args) {
    this.args = args;
    setOwner(this, owner);
  }

  // ...
}
```

Thanks

**Comment by sukima** [comment]
Sorry, I don't have enough knowledge to understand this request. Are you up for maybe a PR as an example? I'll likely just merge without much understanding as I trust others more then I trust myself. :grin:
